export const CONTACT_MESSAGE_MIN_LENGTH = 20;
export const CONTACT_NAME_MAX_LENGTH = 120;
export const CONTACT_EMAIL_MAX_LENGTH = 160;
export const CONTACT_SUBJECT_MAX_LENGTH = 160;
export const CONTACT_MESSAGE_MAX_LENGTH = 5000;
